export const CERTIFICATIONS = [
  {
    title: "Docker - SWARM — SERVICES — STACKS - Hands-on",
    issuer: "KodeKloud",
    date: "Feb 2026",
    categoria: "Course",
    area: "DevOps",
    credential: "https://learn.kodekloud.com/user/certificate/c05aa30a-601c-420c-924e-a56cbd49c44c",
  },
  {
    title: "GitHub Actions Certification",
    issuer: "KodeKloud",
    date: "Sep 2025",
    categoria: "Course",
    area: "DevOps",
    credential: "https://learn.kodekloud.com/user/certificate/205d354c-3eeb-4717-8e8d-e0bda31ff43e",
  },
  {
    title: "GitLab CI/CD: Architecting, Deploying, and Optimizing Pipelines,",
    issuer: "KodeKloud",
    date: "Sep 2025",
    categoria: "Course",
    area: "DevOps",
    credential: "https://learn.kodekloud.com/user/certificate/d403e4b0-f73a-4c27-a979-0cf8f7a4a89f",
  },
  {
    title: "Amazon Elastic Container Service (AWS ECS)",
    issuer: "KodeKloud",
    date: "Feb 2025",
    categoria: "Course",
    area: "DevOps",
    credential: "https://learn.kodekloud.com/user/certificate/ebb51289-3ac5-4f36-a28a-0ecf4a6562a7",
  },
  {
    title: "GCP Cloud Digital Leader Certification",
    issuer: "KodeKloud",
    date: "Sep 2025",
    categoria: "Course",
    area: "DevOps",
    credential: "https://learn.kodekloud.com/user/certificate/9a84963d-f984-49e4-90cb-734ce55ef5c4",
  },
  {
    title: "Introduction to Amazon Virtual Private Cloud (VPC)",
    issuer: "AWS",
    date: "Mar 2026",
    categoria: "Course",
    area: "Cloud Computing",
    credential: "/files/aws1.pdf",
  },
];
